version: "3.8"

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SQLITE_DB=./blog.sqlite
    ports:
      - "8080:8080"
    # volumes:
    #   - ./blog.sqlite:/blog/data/blog.sqlite
