FROM rust:1.82.0
WORKDIR /app

RUN apt-get update && apt-get install nodejs npm -y
RUN cargo install cargo-watch
COPY . .

RUN mv .cargo/config.docker.toml .cargo/config.toml

EXPOSE 8080

CMD [ "cargo", "watch", "-x", "run" ]
