[tasks.buildcss]
command = "npx"
args = ["tailwindcss", "-i", "./assets/input.css", "-o", "./assets/output.css"]

[tasks.watch]
command = "cargo"
args = ["watch", "-q", "-x", "", "-x", "run"]
dependencies = ["buildcss"]

[tasks.run]
command = "cargo"
args = ["watch", "-s", "cargo make buildcss", "-s", "cargo run"]
