[env]
RUST_LOG = "debug"
RUST_ENV = "development"
SERVER_PORT = "8080"
SERVER_HOST = "0.0.0.0"
SQLITE_DB_PATH = "./blog.sqlite"
TRACER_URL = "http://jaeger:4317"
BLOG_CONFIG_PATH = "/app/blog.config.toml"

[registries]
invisible-matrix = { index = "https://github.com/vitordeoliveira/cargo_repository.git" }
