[env]
RUST_LOG = "debug"
RUST_ENV = "development"
SERVER_PORT = "8080"
SERVER_HOST = "127.0.0.1"
SQLITE_DB_PATH = "./data/blog.sqlite"
TRACER_URL = "http://localhost:4317"
BLOG_CONFIG_PATH = "~/Studie/blog/blog.config.toml"

[registries]
invisible-matrix = { index = "https://github.com/vitordeoliveira/cargo_repository.git" }
